### PR TITLE
add support for rendering array of hotspots

### PR DESCRIPTION
**Pull request by jstorm31**
I need to render an array of dynamic hotspots in a project where I use the library:
```
<Pannellum ...>
   <Pannellum.Hotspot ... text="static hotspot" />
   {hotspots.map(hotspot => <Pannellum.Hotspot {...hotspot} />}
</Pannellum>
```
The result has been an error, because current implementation does not take an array as a child of `Pannellum` component in account.

So I flatmapped `children` to be a 1D array of hotspots.

### CODE REVIEW

**Comment by farminf** [comment]
It's already accepting an array, if you need to pass a nested array, you can make it flat before, then pass it to the component, honestly, I don't see any value in this because it is a very edge case.

**Comment by jstorm31** [comment]
Yes, I can prepare an array of hotspots and then pass it as a child, but the way above seems more convenient to me. Moreover, the one-line change won't add any complexity and will still work for other cases.

**Comment by farminf** [comment]
ok, since it hasn't any breaking changes and makes more convenient, I merge this

**Comment by jstorm31** [comment]
Great, thanks! Are you going to release it or wait for more changes at once?

**Comment by farminf** [comment]
It's on develop now, yeah I'll wait since it's minor.

**Pull request merged**
